language: php
php:
- 7.0
- 5.6
- 5.5
- 5.4
- 5.3
- hhvm
install: composer install --dev --prefer-source -n
after_script:
- vendor/bin/test-reporter
env:
  global:
  - secure: fbcAUnwtyv0MCd9OATp2MFPmlwVuv5LYVL7b/taO1ZQUHK7X3qSKbc/bP3RblTu3GMoSahjXK0wv5k/FeJoHHm/J3KkcOcnQH3VctVK+eYhDHdvfRLjm+RkwZ+bOzxVultEhh0r8sl9sHDAv76W7CXwLT8c4wrGtMixELP3oPDCyVgRL1F7ZcB5sTf3oJD3vMU1cNBmFwtnSkid85pt4cz/F0W1JSSvGVpAnclDeH93E6EXObPjrFy8BYJ2DaCobhqiEpzgkaoellb1ds+qTnPpq9qnNAk8xOlz+tueMtLSFNi1UAhSm2+v1i83J/BmmrDTN7xbdO2U0hvjFpYPMZspn6Jg0MnvF+zD9bLTAneP64VzLiGr3tO3CVDXxwLcMgr4fSuCPdsL3aiuq6L42TmhZR6fm5NljiGeXiDLvnKSGkf5jBBnTr+sNF2qJ8r3DxADwUZUdq+8rER3L6NocmRUzBWL+oxDR+/TL7ksr8wYdE/OsumDYnf/ojg9fi6djUW3k0PQVuO5+cpMUIeVJm44Xbd3lVg+0MUQlwLQ0D5A+0y8Fcwq1VcZmwHKIRHDTzjxADgJeE1lmXRLWS/gM8kRyJRFyGpdZtxTxZspysxB1zA28K4NisiCoPvCGQXStixhVNHKTe5QBk+ZrEurEAbv+SpYNgv5dzCXzMy+AxMg=
