language: php
php:
- 7.0
- 5.6
- 5.5
- 5.4
- 5.3
- hhvm
install: composer install --dev --prefer-source -n
after_script:
- vendor/bin/test-reporter
env:
  global:
    secure: ffQ3WKwYchLv994E5gBB6HSyCswOnUFgnCIcw7o6yKq+JksNeKHP1Q1wmjZ3cwpA/mqAr0FnnZWN/ycyiip9aqVYn0dQZCJjRjyTAq1k0EkYoBi0jfBgFyS9nbtMlirelk30034A5AELBF2h5S0icjl7u2hDXnLeRXs8BbchcsX6noCk5XnpCzWqk5d+LI0/4C7DNJgzLQlzvNDS1gfHAWS0RDGLaK+qjFFXw2oyVa74bRH7lnHess17RMn9zGEb3gOZoEd17bporV8Zn0bGTjdyPB5S9bLXDqHHMxlFNunOtGD8W5AsOTU62ONWUwJeRutng3zyNiCMcv68LIHV8LHL3bG5nPyYvax7Z5ZnHxs+2zme0arobKPa2ZxDzGr4jIFnRaGkShqjabAPANy0eCoQX53Fw9cpIrY6KQy1p8khY5l9HjKJduiaVqg5rk8bKOUXpjt46ePiuI+0z49Nw+1D3UKvrzVYrSLn12u6xDuSXAa1r67plAuRBRuu3600LAj0WOTaPWzJvzS+GnpO42/2oyGtdJ9ZPudwSe6GDPHoIL610xHGN3MLLSCEfMKLgWs5EVVJafiStas7wcBFzzSlssafUrMauczOAJLgDZMP++TkjJqDoqSwpXxs5ldqSG8Xjp75ohTUnoUeXJ11D7AtSc+S6zQAUsk7Xnv+ZlM=
